# Generated by Django 4.2.25 on 2025-11-03 16:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='tienda_cate_slug_e4b3f9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='tienda_prod_slug_9feef9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='tienda_prod_is_acti_1b0595_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Existencias'),
        ),
    ]
